# Generated by Django 4.2 on 2023-05-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='auther',
            new_name='author',
        ),
    ]
