# Generated by Django 4.2 on 2023-05-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_tag_article_tags'),
        ('recipes', '0003_alter_ingredient_recipe_alter_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='articles.tag'),
        ),
    ]
